sistemaDeGestaoDeServicosPublicos/Chamados/urls.py
from django.contrib import admin
from django.urls import include, path
from django.contrib.auth import views as auth_views
from django.views.generic.base import TemplateView
from . import views

app_name = 'Chamados'

urlpatterns = [
    path('cadastrarTipoChamado/', views.CadastroTipoChamado, name='cadastro_tipo_chamado'),
    path('listarTiposDeChamado/', views.tiposChamadosList, name='lista_tipo_chamado'),
    path('atualizarTiposDeChamado/<int:pk>', views.atualizarTipoChamado, name='tipo_chamado_atualizar'),
    path('excluirTipoDeChamado/<int:pk>', views.DeletarTipoChamado.as_view(),name='tipo_chamado_deletar'),
    ####
    path('cadastrarStatusChamado/', views.CadastrarStatus.as_view(), name='cadastro_status_chamado'),
    path('listarStatusChamado/', views.ListaStatus, name='lista_status_chamado'),
    path('atualizarStatusChamado/<int:pk>', views.atualizarStatus, name='status_atualizar'),
    path('excluirStatusChamado/<int:pk>', views.DeletarStatus.as_view(),name='status_deletar'),
    ####
    path('cadastrarChamado/', views.CadastroChamado, name='cadastro_chamado'),
    path('listarChamado/<int:pk>', views.ListChamados.as_view(), name='lista_chamado'),
    path('atualizarChamado/<int:pk>', views.atualizarChamado, name='atualiza_chamado'),
    path('<int:pk>/<int:statusChamado>', views.FiltrarChamados.as_view(), name='filtrar_chamados'),
    path('ajax-search/<str:search_string>', views.home_ajax_search, name='pesquisa'),
    path('Chamadodetalhado/<int:pk>', views.detalheChamado, name='chamado_detalhado'),

]

sistemaDeGestaoDeServicosPublicos/Orgao/urls.py
from django.contrib import admin
from django.urls import include, path
from django.contrib.auth import views as auth_views
from django.views.generic.base import TemplateView
from . import views


app_name = 'Orgao'

urlpatterns = [
    #path('', views.index, name='index'),
    path('index_orgao/semosp',views.indexOrgao, name='orgao_index'),
    #path('index_orgao/', views.CriarCadastro.as_view(), name='orgao_index'),
    path('escolheLotacao/', views.retornaLotacao, name='retorna_Lotacao'),
    

    ###
    path('cadastrarTipoLotacao/', views.CadastrarTipoLotacao.as_view(), name='cadastro_Tipo_Lotacao'),
    path('TiposLotacao/', views.TipoLotacaoList, name='tipos_lotacao'),
    path('orgao/atualizarTipoLotacao/<int:pk>', views.AtualizarTipoLotacao.as_view(),name='Tipo_lotacao_atualizar'),
    path('orgao/excluirTipoLotacao/<int:pk>', views.DeletarTipoLotacao.as_view(),name='tipo_lotacao_deletar'),

    ###
    path('cadastrarOrgao/', views.CriarOrgao.as_view(), name='cadastro_orgao'),
    path('OrgaoDados/', views.orgaoList, name='dados_orgao'),
    path('orgao/atualizar/<int:idOrgao>', views.atualizaOrgao,name='orgao_atualizar'),
   
    ###
    path('cadastrarLotacao/', views.CadastroLotacao, name='cadastro_Lotacao'),
    path('listarLotacoes/', views.LotacaoList, name='lista_lotacao'),
    path('atualizarLotacao/<int:idLotacao>', views.atualiza_Lotacao, name='lotacao_atualizar'),
    path('orgao/excluirLotacao/<int:pk>', views.DeletarLotacao.as_view(),name='lotacao_deletar'),
    
    ###
    path('listarChamadosOrgao/', views.ListaOrgaoChamado, name='lista_chamados_orgao'),
    ##path('atualizarChamadosOrgao/<int:pk>', views.atualizarChamadoOrgao, name='atualizar_chamados_orgao'),
    path('gerenciar/chamado/<int:pk>/', views.atualizarChamadoOrgao, name='atualizar_chamados_orgao'),
    path('detalhes/chamado/<int:pk>/', views.detalheChamadoOrgao, name="chamado_detalhado"),
    path('Cadastrar/ocorrencias/chamado/<int:pk>/', views.CadastroOcorrenciasChamado, name='cadastrar_ocorrencias_chamados'),


    
   
]

sistemaDeGestaoDeServicosPublicos/sistemaDeGestaoDeServicosPublicos/urls.py
from django.contrib import admin
from django.urls import include, path
from django.conf.urls.static import static
from django.conf import settings
from django.contrib.auth import views as auth_views
from django.views.generic.base import TemplateView

urlpatterns = [
    path('Usuario/', include('Usuario.urls')),
    path('Chamados/', include('Chamados.urls')),
    path('Orgao/', include('Orgao.urls')),
    path('admin/', admin.site.urls),
    path('accounts/', include('django.contrib.auth.urls')),
    path('', TemplateView.as_view(template_name='sistemaDeGestaoDeServicosPublicos/index1.html'), name="index"),
    path('auth/', include('social_django.urls', namespace='social')),
]+ static(settings.MEDIA_URL, document_root=settings.MEDIA_ROOT)

sistemaDeGestaoDeServicosPublicos/Chamados/forms.py
from django import forms
from django.contrib.auth.models import User
from django.contrib.auth.forms import UserCreationForm
from .models import Orgao, TipoChamado, Status, OcorrenciasChamado, Chamado

class CadastroTiposChamadosForm(forms.ModelForm):
     class Meta:
        model = TipoChamado
        fields = '__all__'

class AtualizarTiposChamadosForm(forms.ModelForm):
    class Meta:
        model = TipoChamado
        fields = '__all__'

class CriarStatusForm(forms.ModelForm):
    class Meta:
        model = Status
        fields = '__all__'

class AtualizarStatusForm(forms.ModelForm):
    class Meta:
        model = Status
        fields = '__all__'

class CadastrarOcorrenciasChamadoForm(forms.ModelForm):
    class Meta:
        model = OcorrenciasChamado
        fields = '__all__'

class CriarChamadoForm(forms.ModelForm):
    class Meta:
        model = Chamado
        fields = '__all__'

class AtualizarChamadoForm(forms.ModelForm):
    class Meta:
        model = Chamado
        fields = '__all__'
        exclude = ('idOrgao', 'idStatus', 'idTipoChamado', 'idUsuario', 'idEndereco', 'numeroProtocolo')

sistemaDeGestaoDeServicosPublicos/Chamados/views.py
from django.views.generic import ListView, CreateView, UpdateView, DeleteView, DetailView
from django.shortcuts import render, redirect, get_object_or_404
from django.http import HttpResponse, HttpResponseRedirect
from django.urls import reverse_lazy, reverse
from .models import Orgao, TipoChamado, Status, OcorrenciasChamado, Chamado, Endereco
from Chamados.forms import CadastroTiposChamadosForm, AtualizarTiposChamadosForm, CriarStatusForm, AtualizarStatusForm, CadastrarOcorrenciasChamadoForm, CriarChamadoForm, AtualizarChamadoForm
from django.core.paginator import Paginator
from django.contrib.auth.models import User
from django.core.paginator import Paginator
from django.contrib.auth.decorators import login_required, permission_required



# Create your views here.
def CadastroTipoChamado(request, pk=None):
    if not request.user.has_perm('TipoChamado.add_TipoChamado'):
        return render(request, 'Orgao/bloqueioDeAcesso.html')
    else:
        if not request.user.is_authenticated:
            return render(request, 'Usuario/acessoNegado.html')
        else:
            if pk:
                pk = get_object_or_404(TipoChamado, id=pk)
            else:
                pk = None
            if request.method == 'POST':
                formEdit = CadastroTiposChamadosForm(request.POST, instance=pk)
                if formEdit.is_valid():
                    formEdit.save()
                    return redirect('Chamados:lista_tipo_chamado')
            else:
                formEdit = CadastroTiposChamadosForm(instance=pk)
                idOrgao = Orgao.objects.all()
                context = {'formEdit': formEdit, 'idOrgao': idOrgao}
            return render(request, 'Chamados/tipoChamado/cadastroTipoChamado.html', context)


def tiposChamadosList(request):
    if not request.user.has_perm('TiposChamados.view_TiposChamados'):
        return render(request, 'Orgao/bloqueioDeAcesso.html')
    else:
        tipo_chamado_list = TipoChamado.objects.all()
        paginator = Paginator(tipo_chamado_list, 5)
        page = request.GET.get('page')
        tipo_chamado_list = paginator.get_page(page)
        context = {'tipo_chamado_list': tipo_chamado_list}
        if not request.user.is_authenticated:
            return render(request, 'Usuario/acessoNegado.html')
        else:
            return render(request, 'Chamados/tipoChamado/listaTiposChamados.html', context)

def atualizarTipoChamado(request, pk=None):
    if not request.user.has_perm('TipoChamado.change_TipoChamado'):
        return render(request, 'Orgao/bloqueioDeAcesso.html')
    else:
        if not request.user.is_authenticated:
            return render(request, 'Usuario/acessoNegado.html')
        else:
            if pk:
                pk = get_object_or_404(TipoChamado, id=pk)
                print("aqui")
            else:
                pk = None

            if request.method == 'POST':
                formEdit = AtualizarTiposChamadosForm(request.POST, instance=pk)
                if formEdit.is_valid():
                    formEdit.save()
                    return redirect('Chamados:lista_tipo_chamado')
            else:
                formEdit = AtualizarTiposChamadosForm(instance=pk)
                idOrgao = Orgao.objects.all()
                context = {'formEdit': formEdit, 'idOrgao': idOrgao}
            return render(request, 'Chamados/tipoChamado/atualizaTipoChamado.html', context)


class DeletarTipoChamado(DeleteView):
    model = TipoChamado
    template_name = "Chamados/tipoChamado/tipo_Chamado_confirm_delete.html"
    success_url = reverse_lazy('Chamados:lista_tipo_chamado')


class CadastrarStatus(CreateView):
    model = Status
    form_class = CriarStatusForm
    template_name = "Chamados/Status/cadastroStatus.html"
    success_url = reverse_lazy("Chamados:lista_status_chamado")


def ListaStatus(request):
    if not request.user.has_perm('Status.view_Status'):
        return render(request, 'Orgao/bloqueioDeAcesso.html')
    else:
        status_list = Status.objects.all()
        paginator = Paginator(status_list, 5)
        page = request.GET.get('page')
        status_list = paginator.get_page(page)
        context = {'status_list': status_list}
        if not request.user.is_authenticated:
            return render(request, 'Usuario/acessoNegado.html')
        else:
            return render(request, 'Chamados/Status/listarStatus.html', context)

def atualizarStatus(request, pk=None):
    if not request.user.has_perm('Status.add_Status'):
        return render(request, 'Orgao/bloqueioDeAcesso.html')
    else:
        if not request.user.is_authenticated:
            return render(request, 'Usuario/acessoNegado.html')
        else:
            if pk:
                pk = get_object_or_404(Status, id=pk)
                print("aqui")
            else:
                pk = None

            if request.method == 'POST':
                formEdit = AtualizarStatusForm(request.POST, instance=pk)
                if formEdit.is_valid():
                    formEdit.save()
                    return redirect('Chamados:lista_status_chamado')
            else:
                formEdit = AtualizarStatusForm(instance=pk)
                context = {'formEdit': formEdit}
            return render(request, 'Chamados/Status/atualizarStatus.html', context)


class DeletarStatus(DeleteView):
    model = Status
    template_name = "Chamados/Status/status_confirm_delete.html"
    success_url = reverse_lazy('Chamados:lista_status_chamado')


class CadastrarOcorrencias(CreateView):
    model = OcorrenciasChamado
    form_class = CadastrarOcorrenciasChamadoForm
    template_name = "Chamados/Ocorrencias/cadastroOcorrenciaasChamado.html"
    success_url = reverse_lazy("Chamados:lista_status_chamado")


def CadastroChamado(request, pk=None):
    if not request.user.is_authenticated:
        return render(request, 'Usuario/acessoNegado.html')
    else:
        if pk:
            pk = get_object_or_404(Chamado, id=pk)
        else:
            pk = None

        if request.method == 'POST':
            formEdit = CriarChamadoForm(request.POST, instance=pk)
            if formEdit.is_valid():
                if pk:
                    formEdit.save()
                else:
                    b = formEdit.save(commit=False)
                    b.numeroProtocolo = Chamado.gerarProtocolo()
                    print(Chamado.gerarProtocolo()+" aqui1122")
                    b.save()
                return redirect(reverse_lazy('Chamados:lista_chamado', kwargs={'pk':request.user.id}))
            else:
                return HttpResponse("aqui")
        else:
            idStatus = Status.objects.filter(id=1)
            idOrgao = Orgao.objects.all()
            idTipoChamado = TipoChamado.objects.all()
            idUsuario = User.objects.filter(id=request.user.id)
            idEndereco = Endereco.objects.filter(idPessoa=request.user.id)
            formEdit = CriarChamadoForm(instance=pk)

            context = {'formEdit': formEdit, 'idOrgao': idOrgao, 'idTipoChamado': idTipoChamado, 'idStatus': idStatus,
                       'idUsuario': idUsuario, 'idEndereco': idEndereco}
            return render(request, 'Chamados/Chamados/criarChamado.html', context)


def ListaChamados(request):
    chamados_list = Chamado.objects.filter(idUsuario=request.user.id)
    paginator = Paginator(chamados_list, 5)
    page = request.GET.get('page')
    chamados_list = paginator.get_page(page)
    context = {'chamados_list': chamados_list}
    if not request.user.is_authenticated:
        return render(request, 'Usuario/acessoNegado.html')
    else:
        return render(request, 'Chamados/Chamados/listarChamado.html', context)


class ListChamados(ListView):
    template_name = "Chamados/Chamados/listarChamado.html"
    context_object_name = 'chamados_list'
    paginate_by = 10000

    def get_queryset(self):
        self.idPessoa =  get_object_or_404(User, id=self.kwargs['pk'])
        return Chamado.objects.filter(idUsuario=self.request.user.id)

    def get_context_data(self, **kwargs):
        context = super().get_context_data(**kwargs)
        context['idPessoa'] = self.idPessoa
        return context

def detalheChamado(request, pk=None):
    if not request.user.is_authenticated:
        return render(request, 'Usuario/acessoNegado.html')
    else:
        if pk:
            chamado = get_object_or_404(Chamado, id=pk)
            idStatus = Status.objects.filter(id=chamado.idStatus.id)
            idOrgao = Orgao.objects.all()
            idTipoChamado = TipoChamado.objects.filter(id=chamado.idTipoChamado.id)
            idUsuario = User.objects.filter(id=request.user.id)
            idEndereco = Endereco.objects.filter(idPessoa=request.user.id)
            nProtocolo = chamado.numeroProtocolo
            dataAbertura = chamado.dataAbertura
            dataConclusao = chamado.dataConclusao
            formEdit = AtualizarChamadoForm(instance=chamado)
            ocorrenciasChamado = OcorrenciasChamado.objects.filter(idChamado=pk)
            context = {'formEdit': formEdit, 'idOrgao': idOrgao, 'idTipoChamado': idTipoChamado, 'idStatus': idStatus,
                       'idUsuario': idUsuario, 'idEndereco': idEndereco, 'nProtocolo' : nProtocolo, 'dataAbertura':dataAbertura, 'dataConclusao': dataConclusao, 'ocorrenciasChamado': ocorrenciasChamado }
            return render(request, 'Chamados/Chamados/detalheChamado.html', context)
        else:
            chamado = None


def atualizarChamado(request, pk=None):
    if not request.user.is_authenticated:
        return render(request, 'Usuario/acessoNegado.html')
    else:
        if pk:
            chamado = get_object_or_404(Chamado, id=pk)
        else:
            chamado = None

        if request.method == 'POST':
            formEdit = AtualizarChamadoForm(request.POST, instance=chamado)
            if formEdit.is_valid():
                formEdit.save()

sistemaDeGestaoDeServicosPublicos/Chamados/templates/Chamados/Status/atualizarStatus.html
<title>SoliServ- Atualizar Status de Chamado</title>
{% extends 'Orgao/index.html' %}
{% block titulo %}
Atualizar Status de Chamado
{% endblock titulo %}
{% block centroOrgao %}
<form method="POST" class="container">
    {% csrf_token %}
    <div class="form-row ">
        <div class="form-group w-100 ">
            <label for="descricao">Descrição do Status:</label>
            <input type="text" class="form-control" id="descricao" name="descricao"
                 maxlength="45" required autofocus {{formEdit.descricao}}>
        </div>
    </div>

    <input type="submit" class="btn bg-gradient-primary text-white  mb-3" title="Cadastrar Status"
        value="Atualizar">
    <a class="btn bg-gradient-primary text-white  mb-3" href="{% url 'Chamados:lista_status_chamado'%}"
        title="Voltar a Página Anterior"><i class="material-icons">undo</i></a>
</form>
{% endblock %}

sistemaDeGestaoDeServicosPublicos/Chamados/templates/Chamados/Status/cadastroStatus.html
<title>SoliServ- Cadastrar Status de Chamado</title>
{% extends 'Orgao/index.html' %}
{% block titulo %}
Cadastro Status de Chamado
{% endblock titulo %}
{% block centroOrgao %}
<form method="POST" class="container mt-1">
    {% csrf_token %}
    <div class="form-row ">
        <div class="form-group w-100 ">
            <label for="descricao">Descrição do Status:</label>
            <input type="text" class="form-control" id="descricao" name="descricao"
                placeholder="Descrição do Tipo de Status" maxlength="45" required autofocus>
        </div>
    </div>

    <input type="submit" class="btn bg-gradient-primary text-white mb-3" title="Cadastrar Status"
        value="Cadastrar">
    <a class="btn  mb-3 bg-gradient-primary text-white " href="{% url 'Chamados:lista_status_chamado'%}"
        title="Voltar a Página Anterior"><i class="material-icons">undo</i></a>
</form>
{% endblock %}

sistemaDeGestaoDeServicosPublicos/Chamados/templates/Chamados/Status/listarStatus.html
<title>SoliServ- Tipos de Status</title>
{% extends "sistemaDeGestaoDeServicosPublicos/index1.html" %}
{% block titulo %}
Tipos de Status
{% endblock titulo %}
{% block centro %}
<main id="Orgao" class="container border">
    <div class="container">
        {% block centroOrgao %}
        <form>
            {% if status_list %}
            <table class="table border mt-3 table-striped"  style="overflow-x: auto">
                <tr>
                    <th>Descrição</th>
                    <th class="text-center">AÇÃO</th>
                </tr>
                {% for status in status_list %}
                <tr>
                    <td>
                        {{status.descricao}}
                    </td>
                    <td class="text-center">
                        <a class="bg-gradient-primary text-white btn-circle"  href="{% url 'Chamados:status_atualizar' status.id %}"
                            title="AtualizarStatus de Chamado">
                            <i class="fas fa-edit"></i>
                        </a>
                        <a class="bg-gradient-danger text-white btn-circle" href="{% url 'Chamados:status_deletar' status.id %}" title="Excluir Status do Chamado">
                            <i class="fas fa-trash"></i>
                        </a>
                    </td>
                </tr>
                {% endfor %}
                {% else %}
                <div class="alert alert-danger mt-3">
                    Não há Dados Cadastrados!
                </div>
                {% endif %}
        </form>
        </table>
        <nav aria-label="text-left pagination  ">
            <ul class="pagination ">
                {% if status_list.has_previous %}
                <li class="page-item">
                    <a class="page-link" style=" color: #4613ac;" href="?page=1" title="Primeira Página">&laquo;
                        Primeira
                    </a>
                </li>
                <li class="page-item">
                    <a class="page-link" style=" color: #4613ac;" title="Página Anterior"
                        href="?page={{ status_list.previous_page_number }}">
                        Anterior
                    </a>
                </li>
                {% endif %}
                <li class="page-item disabled">
                    <a class="page-link" href="#">
                        Página {{ status_list.number }} de {{ status_list.paginator.num_pages }}
                    </a>
                </li>
                {% if status_list.has_next %}
                <li class="page-item">
                    <a class="page-link" style=" color: #4613ac;" title="Próxima Página"
                        href="?page={{ status_list.next_page_number }}">
                        Próxima
                    </a>
                </li>
                <li class="page-item">
                    <a class="page-link" title="Ultima Página" style=" color: #4613ac;"
                        href="?page={{status_list.paginator.num_pages }}">
                        Última &raquo;
                    </a>
                </li>
                {% endif %}
            </ul>
        </nav>
        <a class="btn bg-gradient-primary text-white mb-3" href="{% url 'Chamados:cadastro_status_chamado'%}"
            title="cadastrar Status de Chamado">
            Cadastro Novo Status
        </a>
        <a class="btn bg-gradient-primary text-white mb-3" href="{% url 'Orgao:orgao_index' %}" 
            title="Voltar a HomePage">
            <i class="material-icons">home</i>
        </a>
    </div>
</main>
{% endblock %}

{% endblock %}

sistemaDeGestaoDeServicosPublicos/Chamados/templates/Chamados/Status/status_confirm_delete.html
<title>SoliServ-Excluir Status</title>

{% extends 'sistemaDeGestaoDeServicosPublicos/index1.html' %}
{% block titulo %}
Remover Status
{% endblock titulo %}
{% block centro %}
{% block centroOrgao %}
<div class="container text-center mt-5">
    <form method="post">{% csrf_token %}
       
        <h6 class="alert alert-danger">Tem certeza que deseja remover o Status  "{{ object }}"?</h6>
        <input type="submit" class="btn bg-gradient-danger text-white mt-3" value="Confirmar">
    </form>
</div>
{% endblock %}
{% endblock%}