sistemaDeGestaoDeServicosPublicos/Chamados/urls.py
from django.contrib import admin
from django.urls import include, path
from django.contrib.auth import views as auth_views
from django.views.generic.base import TemplateView
from . import views

app_name = 'Chamados'

urlpatterns = [
    path('cadastrarTipoChamado/', views.CadastroTipoChamado, name='cadastro_tipo_chamado'),
    path('listarTiposDeChamado/', views.tiposChamadosList, name='lista_tipo_chamado'),
    path('atualizarTiposDeChamado/<int:pk>', views.atualizarTipoChamado, name='tipo_chamado_atualizar'),
    path('excluirTipoDeChamado/<int:pk>', views.DeletarTipoChamado.as_view(),name='tipo_chamado_deletar'),
    ####
    path('cadastrarStatusChamado/', views.CadastrarStatus.as_view(), name='cadastro_status_chamado'),
    path('listarStatusChamado/', views.ListaStatus, name='lista_status_chamado'),
    path('atualizarStatusChamado/<int:pk>', views.atualizarStatus, name='status_atualizar'),
    path('excluirStatusChamado/<int:pk>', views.DeletarStatus.as_view(),name='status_deletar'),
    ####
    path('cadastrarChamado/', views.CadastroChamado, name='cadastro_chamado'),
    path('listarChamado/<int:pk>', views.ListChamados.as_view(), name='lista_chamado'),
    path('atualizarChamado/<int:pk>', views.atualizarChamado, name='atualiza_chamado'),
    path('<int:pk>/<int:statusChamado>', views.FiltrarChamados.as_view(), name='filtrar_chamados'),
    path('ajax-search/<str:search_string>', views.home_ajax_search, name='pesquisa'),
    path('Chamadodetalhado/<int:pk>', views.detalheChamado, name='chamado_detalhado'),

]

sistemaDeGestaoDeServicosPublicos/Orgao/urls.py
from django.contrib import admin
from django.urls import include, path
from django.contrib.auth import views as auth_views
from django.views.generic.base import TemplateView
from . import views


app_name = 'Orgao'

urlpatterns = [
    #path('', views.index, name='index'),
    path('index_orgao/semosp',views.indexOrgao, name='orgao_index'),
    #path('index_orgao/', views.CriarCadastro.as_view(), name='orgao_index'),
    path('escolheLotacao/', views.retornaLotacao, name='retorna_Lotacao'),
    

    ###
    path('cadastrarTipoLotacao/', views.CadastrarTipoLotacao.as_view(), name='cadastro_Tipo_Lotacao'),
    path('TiposLotacao/', views.TipoLotacaoList, name='tipos_lotacao'),
    path('orgao/atualizarTipoLotacao/<int:pk>', views.AtualizarTipoLotacao.as_view(),name='Tipo_lotacao_atualizar'),
    path('orgao/excluirTipoLotacao/<int:pk>', views.DeletarTipoLotacao.as_view(),name='tipo_lotacao_deletar'),

    ###
    path('cadastrarOrgao/', views.CriarOrgao.as_view(), name='cadastro_orgao'),
    path('OrgaoDados/', views.orgaoList, name='dados_orgao'),
    path('orgao/atualizar/<int:idOrgao>', views.atualizaOrgao,name='orgao_atualizar'),
   
    ###
    path('cadastrarLotacao/', views.CadastroLotacao, name='cadastro_Lotacao'),
    path('listarLotacoes/', views.LotacaoList, name='lista_lotacao'),
    path('atualizarLotacao/<int:idLotacao>', views.atualiza_Lotacao, name='lotacao_atualizar'),
    path('orgao/excluirLotacao/<int:pk>', views.DeletarLotacao.as_view(),name='lotacao_deletar'),
    
    ###
    path('listarChamadosOrgao/', views.ListaOrgaoChamado, name='lista_chamados_orgao'),
    ##path('atualizarChamadosOrgao/<int:pk>', views.atualizarChamadoOrgao, name='atualizar_chamados_orgao'),
    path('gerenciar/chamado/<int:pk>/', views.atualizarChamadoOrgao, name='atualizar_chamados_orgao'),
    path('detalhes/chamado/<int:pk>/', views.detalheChamadoOrgao, name="chamado_detalhado"),
    path('Cadastrar/ocorrencias/chamado/<int:pk>/', views.CadastroOcorrenciasChamado, name='cadastrar_ocorrencias_chamados'),


    
   
]

sistemaDeGestaoDeServicosPublicos/sistemaDeGestaoDeServicosPublicos/urls.py
from django.contrib import admin
from django.urls import include, path
from django.conf.urls.static import static
from django.conf import settings
from django.contrib.auth import views as auth_views
from django.views.generic.base import TemplateView

urlpatterns = [
    path('Usuario/', include('Usuario.urls')),
    path('Chamados/', include('Chamados.urls')),
    path('Orgao/', include('Orgao.urls')),
    path('admin/', admin.site.urls),
    path('accounts/', include('django.contrib.auth.urls')),
    path('', TemplateView.as_view(template_name='sistemaDeGestaoDeServicosPublicos/index1.html'), name="index"),
    path('auth/', include('social_django.urls', namespace='social')),
]+ static(settings.MEDIA_URL, document_root=settings.MEDIA_ROOT)

sistemaDeGestaoDeServicosPublicos/Orgao/forms.py
from django import forms
from django.contrib.auth.models import User
from django.contrib.auth.forms import UserCreationForm
from .models import Orgao, TipoLotacao, Lotacao
from Chamados.models import Chamado, OcorrenciasChamado


class CadastroOrgaoForm(forms.ModelForm):
    def __init__(self, *args, **kwargs):
        super(CadastroOrgaoForm, self).__init__(*args, **kwargs)
        self.fields['nomeOrgao'].widget.attrs = {
        'class': 'form-group form-control', 'type': 'text', 'placeholder': 'digite o nome da Secretaria'}
        self.fields['descricao'].widget.attrs = {
        'class': 'form-group form-control', 'type': 'text', 'placeholder': 'informe uma Descricao'}
        self.fields['emailOrgao'].widget.attrs = {'class': 'form-group form-control',
                                              'type': 'text', 'placeholder': 'informe o email da secretaria a ser cadastrada'}
        self.fields['nomeResponsavelOrgao'].widget.attrs = {
        'class': 'form-group form-control', 'type': 'text', 'placeholder': 'informe o nome do responsável pela secretaria'}
        self.fields['telefoneOrgao'].widget.attrs = {
        'class': 'form-group form-control', 'type': 'text', 'placeholder': 'informe o telefone da secretaria a ser cadastrada'}
        self.fields['enderecoOrgao'].widget.attrs = {
        'class': 'form-group form-control', 'type': 'text', 'placeholder': 'informe o endereco da secretaria a ser cadastrada'}

    class Meta:
        model = Orgao
        fields = '__all__'

class CadastroTipoLotacaoForm(forms.ModelForm):
    class Meta:
        model = TipoLotacao
        fields = '__all__'

class CadastroLotacaoForm(forms.ModelForm):
    class Meta:
        model = Lotacao
        fields = '__all__'

class AtualizarLotacaoForm(forms.ModelForm):
    class Meta:
        model = Lotacao
        fields = '__all__'

class atualizarChamadosOrgaoForm(forms.ModelForm):
    class Meta:
        model = Chamado
        fields = '__all__'
        exclude = ('idOrgao','idTipoChamado', 'idUsuario', 'idEndereco', 'numeroProtocolo')

class CadastrarOcorrenciasChamadoForm(forms.ModelForm):
    class Meta:
        model = OcorrenciasChamado
        fields = '__all__'
     
        

sistemaDeGestaoDeServicosPublicos/Orgao/views.py
import json
from social_django.models import UserSocialAuth
from django.views.generic import ListView, CreateView, UpdateView, DeleteView, DetailView
from django.shortcuts import render, redirect, get_object_or_404
from django.http import HttpResponse, HttpResponseRedirect
from django.urls import reverse_lazy, reverse
from .models import Lotacao, Orgao, TipoLotacao
from Orgao.forms import CadastroOrgaoForm, CadastroTipoLotacaoForm, CadastroLotacaoForm, AtualizarLotacaoForm,atualizarChamadosOrgaoForm, CadastrarOcorrenciasChamadoForm
from django.core.paginator import Paginator
from django.contrib.auth.models import User, Group
from django.core.exceptions import PermissionDenied
from Chamados.models import Chamado, Status, TipoChamado, OcorrenciasChamado
from Usuario.models import Endereco
from Chamados.forms import AtualizarChamadoForm

# Create your views here.


def indexOrgao(request):
    idOrgao = request.session['idVinculo']
    if not request.user.is_authenticated:
        return render(request, 'Usuario/acessoNegado.html')
    else:
        orgaoSelecionado = get_object_or_404(Orgao, pk=idOrgao)
        context = {'orgaoSelecionado':  orgaoSelecionado}
        return render(request, 'Orgao/index.html', context)


def retornaLotacao(request):
    context= {}
    try:
        picture = UserSocialAuth.objects.get(uid=request.user.email)
        path_dump = json.dumps(picture.extra_data)
        path_load = json.loads(path_dump)
        picture = path_load["picture"]
        context = {'picture': picture}
        request.session['profile_picture'] = picture
    except:
        pass
    lotacao = Lotacao.objects.filter(idUsuario=request.user.id)
    context = {'userServidor': lotacao}
    if not request.user.is_authenticated:
        return render(request, 'Usuario/acessoNegado.html')
    else:
        if request.method == 'POST':
            idOrgaoVinculo = request.POST.get('idOrgao')
            orgaoVinculo = get_object_or_404(Orgao, pk=idOrgaoVinculo)
            request.session['idVinculo'] = idOrgaoVinculo
            request.session['nomeVinculo'] = orgaoVinculo.nomeOrgao
            return redirect('Orgao:orgao_index')

        else:
            if len(lotacao) == 0:
                return HttpResponseRedirect(reverse('index'))
            else:
                request.session['temVinculo'] = 'yes'
                return render(request, 'Orgao/escolheVinculo.html', context)
        return HttpResponse(request.POST.get('idOrgao'))


class CriarOrgao(CreateView):
    model = Orgao
    form_class = CadastroOrgaoForm
    template_name = "Orgao/cadastroOrgao.html"
    success_url = reverse_lazy("Orgao:orgao_index")


def orgaoList(request):
    if not request.user.has_perm('Orgao.view_Orgao'):
        return render(request, 'Orgao/bloqueioDeAcesso.html')
    else:
        orgao_list = Orgao.objects.all()
        context = {'orgao_list': orgao_list}
        if not request.user.is_authenticated:
            return render(request, 'Usuario/acessoNegado.html')
        else:
            return render(request, 'Orgao/dadosOrgao.html', context)


def atualizaOrgao(request, idOrgao=None):
    if not request.user.has_perm('Orgao.change_Orgao'):
        return render(request, 'Orgao/bloqueioDeAcesso.html')
    else:
        if not request.user.is_authenticated:
            return render(request, 'Usuario/acessoNegado.html')
        else:
            if idOrgao:
                idOrgao = get_object_or_404(Orgao, id=idOrgao)
                print("aqui")
            else:
                idOrgao = None
            if request.method == 'POST':
                formEdit = CadastroOrgaoForm(request.POST, instance=idOrgao)
                if formEdit.is_valid():
                    formEdit.save()
                    return redirect('Orgao:dados_orgao')
            else:
                formEdit = CadastroOrgaoForm(instance=idOrgao)
                context = {'formEdit': formEdit}
            return render(request, 'Orgao/atualizarOrgao.html', context)


class CadastrarTipoLotacao(CreateView):
    model = TipoLotacao
    form_class = CadastroTipoLotacaoForm
    template_name = "TipoLotacao/cadastroTipoLotacao.html"
    success_url = reverse_lazy("Orgao:tipos_lotacao")


def TipoLotacaoList(request):
    if not request.user.has_perm('TipoLotacao.view_TipoLotacao'):
        return render(request, 'Orgao/bloqueioDeAcesso.html')
    else:
        if not request.user.is_authenticated:
            return render(request, 'Usuario/acessoNegado.html')
        else:
            tipo_lotacao_list = TipoLotacao.objects.all()
            paginator = Paginator(tipo_lotacao_list, 5)
            page = request.GET.get('page')
            tipo_lotacao_list = paginator.get_page(page)
            context = {'tipo_lotacao_list': tipo_lotacao_list}
            if not request.user.is_authenticated:
                return render(request, 'Usuario/acessoNegado.html')
            else:
                return render(request, 'TipoLotacao/tiposLotacao.html', context)


class AtualizarTipoLotacao(UpdateView):
    model = TipoLotacao
    form_class = CadastroTipoLotacaoForm
    template_name = "TipoLotacao/atualizarTipoLotacao.html"
    success_url = reverse_lazy('Orgao:tipos_lotacao')


class DeletarTipoLotacao(DeleteView):
    model = TipoLotacao
    template_name = "TipoLotacao/tipoLotacao_Confirm_delete.html"
    success_url = reverse_lazy('Orgao:tipos_lotacao')


def CadastroLotacao(request, idL=None):
    if not request.user.has_perm('Lotacao.add_Lotacao'):
        return render(request, 'Orgao/bloqueioDeAcesso.html')
    else:
        if not request.user.is_authenticated:
            return render(request, 'Usuario/acessoNegado.html')
        else:
            if idL:
                idL = get_object_or_404(Lotacao, id=idL)
            else:
                idL = None

                formEdit = CadastroLotacaoForm(request.POST, instance=idL)
            if request.method == 'POST':

                if formEdit.is_valid():
                    usuario = User.objects.get(id=request.POST.get('idUsuario'))
                    tipo_Lotacao =TipoLotacao.objects.get(id = request.POST.get('idTipoLotacao'))
                    grupo = Group.objects.get(name= tipo_Lotacao.descricao)
                    usuario.groups.add(grupo)
                    formEdit.save()
                    return redirect('Orgao:tipos_lotacao')
            else:
                tipoLotacao = TipoLotacao.objects.all()
                idUsuario = User.objects.all()
                idOrgao = Orgao.objects.all()
                context = {'formEdit': formEdit, 'tipoLotacao': tipoLotacao,
                        'idUsuario': idUsuario, 'idOrgao': idOrgao}
            return render(request, 'Lotacao/cadastroLotacao.html', context)


def LotacaoList(request):
    if not request.user.has_perm('Lotacao.add_Lotacao'):
        return render(request, 'Orgao/bloqueioDeAcesso.html')
    else:
        if not request.user.is_authenticated:
            return render(request, 'Usuario/acessoNegado.html')
        else:
            lotacao_list = Lotacao.objects.all()
            paginator = Paginator(lotacao_list, 6)
            page = request.GET.get('page')
            lotacao_list = paginator.get_page(page)
            context = {'lotacao_list': lotacao_list}
            if not request.user.is_authenticated:
                return render(request, 'Usuario/acessoNegado.html')
            else:
                return render(request, 'Lotacao/lotacaoList.html', context)

def atualiza_Lotacao(request, idLotacao=None):
    if not request.user.has_perm('Lotacao.add_Lotacao'):
        return render(request, 'Orgao/bloqueioDeAcesso.html')
    else:
        if not request.user.is_authenticated:
            return render(request, 'Usuario/acessoNegado.html')
        else:
            tipoLotacao = TipoLotacao.objects.all()
            idUsuario = User.objects.all()
            idOrgao = Orgao.objects.all()
            if idLotacao:
                idLotacao = get_object_or_404(Lotacao, id=idLotacao)
                print("aqui")
            else:
                idLotacao = None
            if request.method == 'POST':
                formEdit = AtualizarLotacaoForm(request.POST, instance=idLotacao)
                if formEdit.is_valid():
                    formEdit.save()
                    return redirect('Orgao:lista_lotacao')
            else:
                formEdit = AtualizarLotacaoForm(instance=idLotacao)
                context = {'formEdit': formEdit, 'tipoLotacao': tipoLotacao,
                        'idUsuario': idUsuario, 'idOrgao': idOrgao}
            return render(request, 'Lotacao/atualizarLotacao.html', context)


class DeletarLotacao(DeleteView):
    model = Lotacao
    template_name = "Lotacao/lotacao_confirm_delete.html"
    success_url = reverse_lazy('Orgao:lista_lotacao')

def ListaOrgaoChamado(request):
    if not request.user.has_perm('Chamado.view_Chamado'):
        return render(request, 'Orgao/bloqueioDeAcesso.html')
    else:
        lista_chamados = Chamado.objects.all()
        paginator = Paginator(lista_chamados, 10000)
        page = request.GET.get('page')
        lista_chamados = paginator.get_page(page)
        context = {'lista_chamados': lista_chamados}
        if not request.user.is_authenticated:
            return render(request, 'Usuario/acessoNegado.html')
        else:
            return render(request, 'ChamadosOrgao/listarChamadosOrgao.html', context)

def atualizarChamadoOrgao(request, pk=None):
    if not request.user.is_authenticated:
        return render(request, 'Usuario/acessoNegado.html')
    else:
        if pk:
            chamado = get_object_or_404(Chamado, id=pk)
        else:
            chamado = None

        if request.method == 'POST':
            formEdit = atualizarChamadosOrgaoForm(request.POST, instance=chamado)
            if formEdit.is_valid():
                formEdit.save()

sistemaDeGestaoDeServicosPublicos/Orgao/templates/Orgao/atualizarTipoLotacao.html
<title>SoliServ- Atualizar Tipo de Lotação</title>
{% extends 'Orgao/index.html' %}
{% block centroOrgao %}
<form method="POST" class="mt-3">
    <div class="col">
        {% csrf_token %}
        {{ form.as_p }}
    </div>
    <input type="submit" class="btn mb-2" style="background-color: #4613ac; color: white;" title="Atualizar Dados"
        value="Atualizar Tipo Lotação">
    <a class="btn  mb-2" href="{% url 'Orgao:orgao_index'%}" style="background: #4613ac; color: white;"
        title="Voltar a HomePage">Página Inicial</a>
</form>
{% endblock %}

sistemaDeGestaoDeServicosPublicos/Orgao/templates/Orgao/dadosOrgao.html
<title>SoliServ- Meus Dados- Semosp</title>
{% extends "sistemaDeGestaoDeServicosPublicos/index1.html" %}
{% block titulo %}
Secretaria Municipal de Obras
{% endblock titulo %}
{% block centro %}
<main id="Orgao" class="container border">
    
    <div class="container">
    {% block centroOrgao %}
    {% if orgao_list %}
    {% for dados in orgao_list %}
    <form>
        <div>
            <div class="mt-3">
                <labelfor="Nome">Nome do Orgão: </label>
                <input style="text-transform: uppercase;" type="text" class="form-control" disabled id="nome"
                    value="{{dados.nomeOrgao}}">
            </div>
            <div class="mt-3">
                <label for="nomeOrgao">Descrição do Orgão:</label>
                <input style="text-transform: uppercase;" type="text" class="form-control" disabled id="SobreNome"
                    value="{{dados.descricao}}">
            </div>
            <div class="mt-3">
                <label  for="email">E-mail do Orgão: </label>
                <input style="text-transform: uppercase;" type="text" class="form-control" disabled id="email"
                    value="{{dados.emailOrgao}}">
            </div>
            <div class="mt-3">
                <label  for="email">Responsável pelo Orgão: </label>
                <input style="text-transform: uppercase;" type="text" class="form-control" disabled id="email"
                    value="{{dados.nomeResponsavelOrgao}}">
            </div>
            <div class="mt-3">
                <label for="email">Endereço do Órgão: </label>
                <input style="text-transform: uppercase;" type="text" class="form-control" disabled id="email"
                    value="{{dados.enderecoOrgao}}">
            </div>
            <div class="mt-3 mb-5">
                <label  for="email">Telefone do Orgão: </label>
                <input style="text-transform: uppercase;" type="text" class="form-control" disabled id="email"
                    value="{{dados.telefoneOrgao}}">
            </div>  
        </div>
        {% if orgao_list == 0 %}
       <a class="btn  mb-3" href="{% url 'Orgao:cadastro_orgao'%}"title="Cadastrar o órgão" style="background: #4613ac; color: white;">Cadastro Orgão</a>
        {% else %} 
        {% endif %}
        <a class="btn  bg-gradient-primary text-white  mb-3" href="{% url 'Orgao:orgao_atualizar' dados.id %}" title="Visualizar os dados do órgão">Atualizar Dados</a>
        <a class="btn   bg-gradient-primary text-white mb-3" href="{% url 'Orgao:orgao_index'%}" title="Voltar a HomePage"><i class="material-icons">home</i></a>
    </form>
    {% endfor %}
    {% endif %} 
    {% endblock %}        
    </div>
</main>
{% endblock %}

sistemaDeGestaoDeServicosPublicos/Orgao/templates/Orgao/funcaoIndisponivel.html
<title>
    SoliServ-Funcao Indisponível
</title>
{% extends "sistemaDeGestaoDeServicosPublicos/index1.html" %}
{% block centro %}
{% block centroOrgao %}
<div class="container text-center alert alert-danger mt-3">
    <p class="">Função em construção!</p>
</div>
<a class="btn  mb-3 text-center bg-gradient-primary text-white" href="{% url 'Orgao:lista_chamados_orgao'%}" title="Lista de Chamados"><i class="material-icons">undo</i></a>
{% endblock %}
{% endblock %}

sistemaDeGestaoDeServicosPublicos/Orgao/templates/Orgao/index.html
<title>SoliServ- Semosp</title>
{% extends "sistemaDeGestaoDeServicosPublicos/index1.html" %}
{% block titulo %}
{{orgaoSelecionado.nomeOrgao}}
{% endblock titulo %}
{% block centro %}
<style>
    #cartoes-orgao:hover {
        border-style: solid;
        border-color: blue;
        border-width: 4px;
    }

    #titulo-cartoes:hover {
        text-decoration: none;
        color: red;
    }

    #cartoes-chamado:hover {
        border-style: solid;
        border-color: yellow;
        border-width: 3px;
    }

    #titulo-chamado:hover {
        text-decoration: none;
        color: red;
    }
</style>
<main id="Orgao" class="container">

    <div class="border">
        {% block centroOrgao %}
        <div class="container border text-center">
            <!-- <h4 class="text-center m-3">Referentes ao Orgão</h4> -->
            <div class="row text-center mt-3">
                <div class="col-xl-3 col-md-6 mb-4 mt-2">
                    <div class="card border-left-primary shadow h-100 py-2" id="cartoes-orgao">
                        <div class="card-body">
                            <div class="row no-gutters align-items-center">
                                <div class="col mr-2">
                                    <div class="text-xs font-weight-bold text-primary text-uppercase mb-1">Orgão</div>
                                    <div class="h5 mb-0 font-weight-bold text-gray-800">
                                        <a id="titulo-cartoes" href="{% url 'Orgao:dados_orgao'%}">
                                            Dados do Orgao
                                        </a>
                                    </div>
                                </div>
                                <div class="col-auto">
                                    <i class="fas fa-table fa-2x text-gray-300"></i>
                                </div>
                            </div>
                        </div>
                    </div>
                </div>

                <div class="col-xl-3 col-md-6 mb-4 mt-2">
                    <div class="card border-left-primary shadow h-100 py-2" id="cartoes-orgao">
                        <div class="card-body">
                            <div class="row no-gutters align-items-center">
                                <div class="col mr-2">
                                    <div class="text-xs font-weight-bold text-primary text-uppercase mb-1">Orgão</div>
                                    <div class="h5 mb-0 font-weight-bold text-gray-800">
                                        <a id="titulo-cartoes" href="{% url 'Orgao:tipos_lotacao'%}">
                                            Tipos de Lotacao
                                        </a>
                                    </div>
                                </div>
                                <div class="col-auto">
                                    <i class="fas fa-table fa-2x text-gray-300"></i>
                                </div>
                            </div>
                        </div>
                    </div>
                </div>

                <div class="col-xl-3 col-md-6 mb-4 mt-2">
                    <div class="card border-left-primary shadow h-100 py-2" id="cartoes-orgao">
                        <div class="card-body">
                            <div class="row no-gutters align-items-center">
                                <div class="col mr-2">
                                    <div class="text-xs font-weight-bold text-primary text-uppercase mb-1">Orgão</div>
                                    <div class="h5 mb-0 font-weight-bold text-gray-800">
                                        <a id="titulo-cartoes" href="{% url 'Orgao:lista_lotacao'%}">
                                            Lotações
                                        </a>
                                    </div>
                                </div>
                                <div class="col-auto">
                                    <i class="fas fa-table fa-2x text-gray-300"></i>
                                </div>
                            </div>
                        </div>
                    </div>
                </div>

            </div>

            <div class="form-row text-center">
                <div class="col-xl-3 col-md-6 mb-4 mt-2">
                    <div class="card border-left-warning shadow h-100 py-2" id="cartoes-chamado">
                        <div class="card-body">
                            <div class="row no-gutters align-items-center">
                                <div class="col mr-2">
                                    <div class="text-xs font-weight-bold text-primary text-uppercase mb-1">Chamado</div>
                                    <div class="h5 mb-0 font-weight-bold text-gray-800">
                                        <a id="titulo-chamado" href="{% url 'Chamados:lista_tipo_chamado' %}">
                                            Tipo de Chamado
                                        </a>
                                    </div>
                                </div>
                                <div class="col-auto">
                                    <i class="fas fa-table fa-2x text-gray-300"></i>
                                </div>
                            </div>
                        </div>
                    </div>
                </div>

                <div class="col-xl-3 col-md-6 mb-4 mt-2">
                    <div class="card border-left-warning shadow h-100 py-2" id="cartoes-chamado">
                        <div class="card-body">
                            <div class="row no-gutters align-items-center">
                                <div class="col mr-2">
                                    <div class="text-xs font-weight-bold text-primary text-uppercase mb-1">Chamado</div>
                                    <div class="h5 mb-0 font-weight-bold text-gray-800">
                                        <a id="titulo-chamado" href="{% url 'Chamados:lista_status_chamado' %}">
                                            Status do Chamado
                                        </a>
                                    </div>
                                </div>
                                <div class="col-auto">
                                    <i class="fas fa-table fa-2x text-gray-300"></i>
                                </div>
                            </div>
                        </div>
                    </div>
                </div>

                <div class="col-xl-3 col-md-6 mb-4 mt-2">
                    <div class="card border-left-warning shadow h-100 py-2" id="cartoes-chamado">
                        <div class="card-body">
                            <div class="row no-gutters align-items-center">
                                <div class="col mr-2">
                                    <div class="text-xs font-weight-bold text-primary text-uppercase mb-1">Chamado</div>
                                    <div class="h5 mb-0 font-weight-bold text-gray-800">
                                        <a id="titulo-chamado" href="{% url 'Orgao:lista_chamados_orgao' %}">
                                            Lista de Chamados
                                        </a>
                                    </div>
                                </div>
                                <div class="col-auto">
                                    <i class="fas fa-table fa-2x text-gray-300"></i>
                                </div>
                            </div>
                        </div>
                    </div>
                </div>
            </div>
        </div>

        {% endblock %}
    </div>
</main>
{% endblock %}

sistemaDeGestaoDeServicosPublicos/Orgao/templates/Orgao/indexOrgaoGerenteGeral.html
<title>SoliServ- Semosp</title>
{% extends "sistemaDeGestaoDeServicosPublicos/index1.html" %}

{% block centro %}

<main id="Orgao" class="container border">

    <div id="tituloOrgao" class="container pb-2 pt-2">
        <h3>Secretaria Municipal de Obras</h3>
    </div>
    <div class="container">
    {% block centroOrgao %}
    <a href="{% url 'Orgao:cadastro_orgao'%}">cadastro Orgao</a>
    {% endblock %}        
    </div>

</main>

{% endblock %}